spring.application.name=backend

# Database Connection Settings
## Create database `testdb` that lives in computer memory `mem`
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 Web Console
## Activate the web page so we can see the database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console